### ISSUE TITLE
Misaligned status register read fails on FreeBSD

### ISSUE THREAD

**Issue by antonrang** [intel/pcm#884]
There’s some code in processDVSec which tries to read 32 bits from byte offset 6 in configuration space. This presumably works on Linux, but the FreeBSD PCI driver rejects this. The following patch fixes this.

```
diff --git a/src/pci.h b/src/pci.h
index ec44e99..d7c0326 100644
--- a/src/pci.h
+++ b/src/pci.h
@@ -261,8 +261,8 @@ void processDVSEC(MatchFunc matchFunc, ProcessFunc processF>
         // std::cerr << "Intel device scan. found " << std::hex << group << ":>
         uint32 status{0};
         PciHandleType h(group, bus, device, function);
-        h.read32(6, &status); // read status
-        if (status & 0x10) // has capability list
+        h.read32(4, &status); // read status
+        if (status & 0x100000) // has capability list
         {
             // std::cerr << "Intel device scan. found "<< std::hex << group <<>
             VSEC header;
```

The current source base is also missing some minor tweaks necessary to build on FreeBSD (mostly the cpu_set_t / cpuset_t definition), but those are trivial.

**Comment by rdementi** [comment]
thank you for reporting the issue with the alignment. As you noted these work on Linux. Will fix asap as recommended to make it work on FreeBSD.

With regards to the cpu_set_t: could you please suggest a change? For some reason our FreeBSD builds are not failing due to this: https://github.com/intel/pcm/actions/workflows/freebsd_build.yml
